PUT http://localhost:8080/hello/put/Rishav?lastName=Thakur


###
POST http://localhost:8080/hello/post
Content-Type: application/json

{
  "firstName": "Rishav",
  "lastName": "Thakur"
}

###
GET http://localhost:8080/hello/param/Rishav

###
GET http://localhost:8080/hello/?name=Rishav

###
GET localhost:8080
