POST http://localhost:8080/hello/post
Content-Type: application/json

{
  "firstName": "Rishav",
  "lastName": "Thakur"
}

###
GET http://localhost:8080/param/Rishav

###
GET http://localhost:8080/query?name=Rishav

###
GET localhost:8080
